//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZC.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds16733757_dbEntities : DbContext
    {
        public qds16733757_dbEntities()
            : base("name=qds16733757_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NZC_ImageInfo> NZC_ImageInfo { get; set; }
        public virtual DbSet<NZC_UserInfo> NZC_UserInfo { get; set; }
    }
}
