//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZC.Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds16733757_dbEntities1 : DbContext
    {
        public qds16733757_dbEntities1()
            : base("name=qds16733757_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NZC_ImageInfo> NZC_ImageInfo { get; set; }
        public DbSet<NZC_UserInfo> NZC_UserInfo { get; set; }
        public DbSet<NZC_LunBoTu> NZC_LunBoTu { get; set; }
    }
}
