//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZC.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class NZC_UserInfo
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Tel { get; set; }
        public string NiCheng { get; set; }
        public int JueSe { get; set; }
    }
}
